### ISSUE TITLE
As bombas de porão não estão no esquema, somente o acionamento

### ISSUE THREAD

**Issue by AlejoPm03** [ZeniteSolar/boat19#4]

**Comment by guilhermecv** [comment]
Duas bombas foram adicionadas

**Comment by joaoantoniocardoso** [comment]
@guilhermecv , consegues adicionar a chave automática também? O nosso módulo MAB19 possui  três portas: `Level_sensor`, `+Pump` e `-Pump`.

**Comment by guilhermecv** [comment]
Conferir alterações

**Comment by gabrielgunthercenteno** [comment]
alterações conferidas
