### ISSUE TITLE
A fonte principal não tem entrada de alimentação

### ISSUE THREAD

**Issue by AlejoPm03** [ZeniteSolar/boat19#5]
A fonte principal, tem duas entradas, uma de alimentação que está conectada diretamente na bateria e outra de ON/OFF

**Comment by joaoantoniocardoso** [comment]
Melhor detalhando, seriam 5 pinos de entrada: polos positivo e negativo da bateria, `enable_gnd` + `enable` para uma chave que liga e desliga a fonte e o CAN.

**Comment by guilhermecv** [comment]
Conferir Alterações
